name: Databricks OIDC Deployment Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    
    env:
      DATABRICKS_HOST: https://dbc-e04d75a2-cdf2.cloud.databricks.com/browse/folders/repos?o=7474654078694076
      DATABRICKS_CLIENT_ID: "96012af9-817d-4867-a2f0-e4d7da458b3a"
      DATABRICKS_AUTH_TYPE: github-oidc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Update Databricks Repo
        run: |
          # あなたのユーザーフォルダ配下のtesting0317を更新
          # パスは Databricks UI の [Repos] > [あなたのフォルダ] > [testing0317] で右クリック→[Copy path]で取得できます
          databricks repos update /Workspace/Repos/ssakaka2026-0203@example.com/testing0317 --branch main
