name: Databricks OIDC Deployment Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    
    env:
      DATABRICKS_HOST: https://dbc-74746540-7869.cloud.databricks.com
      DATABRICKS_CLIENT_ID: "96012af9-817d-4867-a2f0-e4d7da458b3a"
      DATABRICKS_AUTH_TYPE: github-oidc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Search Correct Repo Path
        run: |
          # ログインできているSPが「見ることができる」リポジトリを一覧表示します
          databricks repos list
